# Generated by Django 5.2.1 on 2025-06-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_invoice_balance_due_invoice_subtotal_invoice_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='balance_due',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='total',
        ),
    ]
